 <!-- 顶部logo -->
    <div data-options="region:'north'" style="height:60px;">
      <div style="font-size:12px;font-fimaly:微软雅黑;background-image:url(../img/logo.png);background-repeat:no-repeat;background-color:#eee;color:#636363;padding-right:20px;padding-top:40px;height:18px;text-align:right">
  		 <label>欢迎您：享悦[管理员]</label>&nbsp;&nbsp;
  		 <a href="../login.html">退出登录</a>
	  </div>
    </div>
    <!-- 底部信息 -->
    <div data-options="region:'south'" style="height:30px;line-height:30px">
      <div align="center" style="background:#eee;font-size:12px">
  		Copyright &copy; 2000-2010 享悦 版权所有
	  </div>